app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(`rmcorr-sampleData` = TRUE)
app$snapshot()
app$uploadFile(`rmcorr-excelFile` = "raz2005.csv")
app$snapshot()
app$setInputs(plotTheme = "theme_light()")
app$snapshot()
app$setInputs(plotPalette = "Spectral")
app$snapshot()
app$setInputs(CIlevel = 0.9)
app$snapshot()
app$setInputs(downloadFormat = "png")
app$snapshotDownload("downloadPlot")
app$setInputs(m2Column = "Age")
app$setInputs(m1Column = "Volume")
app$snapshot()
