app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(`rmcorr-sampleData` = TRUE)
app$setInputs(plotPalette = "PRGn")
app$setInputs(plotTitle = "Title")
app$setInputs(titleFontSize = 30)
app$setInputs(plotLegend = TRUE)
app$setInputs(legendTitle = "Participants")
app$setInputs(addText = TRUE)
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshotDownload("downloadPlot")
app$uploadFile(`rmcorr-excelFile` = "raz2005.csv")
app$snapshot()
